# Generated by Django 5.0.3 on 2024-05-15 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0009_delete_postmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('uploaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medias.media')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'verbose_name': '게시글 첨부 사진/영상',
                'verbose_name_plural': '게시글 첨부 사진/영상들',
                'ordering': ['post__created_at'],
            },
            bases=('medias.media',),
        ),
    ]
