# Generated by Django 5.0.3 on 2024-05-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글들'},
        ),
    ]
