# Generated by Django 5.0.3 on 2024-05-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_userboardprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userboardprofile',
            options={'ordering': ['user__username'], 'verbose_name': '유저의 게시판 관련 정보', 'verbose_name_plural': '유저의 게시판 관련 정보들'},
        ),
    ]
