# Generated by Django 5.0.3 on 2024-05-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_userboardprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseboard',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
