# Generated by Django 5.0.3 on 2024-05-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SYSTEM', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '기본 게시판',
                'verbose_name_plural': '기본 게시판들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SYSTEM', max_length=255)),
                ('profile', models.URLField(default='SYSTEM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubBoard',
            fields=[
                ('baseboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.baseboard')),
            ],
            options={
                'verbose_name': '동아리 게시판',
                'verbose_name_plural': '동아리 게시판들',
                'ordering': ['created_at'],
            },
            bases=('posts.baseboard',),
        ),
        migrations.CreateModel(
            name='OrganizationBoard',
            fields=[
                ('baseboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.baseboard')),
            ],
            options={
                'verbose_name': '학교/단체 게시판',
                'verbose_name_plural': '학교/단체 게시판들',
                'ordering': ['created_at'],
            },
            bases=('posts.baseboard',),
        ),
        migrations.CreateModel(
            name='RegionBoard',
            fields=[
                ('baseboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.baseboard')),
            ],
            options={
                'verbose_name': '지역 게시판',
                'verbose_name_plural': '지역 게시판들',
                'ordering': ['created_at'],
            },
            bases=('posts.baseboard',),
        ),
    ]
