# Generated by Django 5.0.3 on 2024-05-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_userpostprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
