# Generated by Django 5.0.3 on 2024-05-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'verbose_name': '게시글 첨부 사진/영상',
                'verbose_name_plural': '게시글 첨부 사진/영상들',
                'ordering': ['post__created_at'],
            },
        ),
    ]
