# Generated by Django 5.0.3 on 2024-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
