# Generated by Django 5.0.3 on 2024-05-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_pending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostMedia',
        ),
    ]
