# Generated by Django 5.0.3 on 2024-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthentication',
            fields=[
                ('auth_id', models.CharField(default='example', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('obj_email', models.CharField(default='@example.com', max_length=128)),
                ('auth_code', models.CharField(max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
