# Generated by Django 5.0.3 on 2024-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.URLField(blank=True, default=''),
        ),
    ]
