# Generated by Django 5.0.3 on 2024-04-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_email', models.EmailField(default='taco@example.com', max_length=254)),
                ('auth_code', models.CharField(max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('auth_type', models.CharField(choices=[('signup', '회원가입'), ('pwreset', '비밀번호리셋')], default='signup', max_length=16)),
            ],
        ),
    ]
