# Generated by Django 5.0.3 on 2024-04-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organization_region_alter_user_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailauthentication',
            options={'ordering': ['sent_at'], 'verbose_name': '가입 인증 메일 발송 기록', 'verbose_name_plural': '가입 인증 메일 발송 기록들'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['created_at'], 'verbose_name': '학교/단체', 'verbose_name_plural': '학교/단체들'},
        ),
        migrations.AlterModelOptions(
            name='organizationemail',
            options={'ordering': ['created_at'], 'verbose_name': '학교/단체 인증용 이메일 주소', 'verbose_name_plural': '학교/단체 인증용 이메일 주소들'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['signup_at'], 'verbose_name': '유저', 'verbose_name_plural': '유저들'},
        ),
    ]
